"""CASE #004 노란 자막 초안 v1 (원본 시각). 화자: C=クリス(아빠) E=エリー(엄마) B=아들(로건/코너, 화면 확인 전) J=일본인 점원.
화자는 목소리 높이(F0)·내용으로 잡은 초안 → 대조 시트로 화면 확인 필수(04 E9-3).
(ep, s0, s1, spk, ja, ko, en)"""
import json
C = [
# 0 첫 장면 (T 7:52-8:01)
("T",469.97,471.41,"E","向こうに行けって、手で合図された","저쪽으로 가라고 손짓했어","He just motioned for us to go to the other side."),
("T",472.17,474.29,"C","人がいる。こっちに行こう","사람이 있네. 이쪽으로 가자","But there's a real person here, so we'll go here."),
("T",474.29,479.90,"C","係の人が案内してくれてる。\\N迷子の外国人は、こっちらしい","직원이 안내해 주네. 길 잃은 외국인은 이쪽인가 봐","There's an actual real person guiding us here, so I think the lost foreigners need to go here"),
("T",1018.45,1020.21,"E","東京へようこそ！","도쿄에 온 걸 환영해!","Welcome to Tokyo!"),
("T",1020.41,1023.65,"E","みんな、着いたよ。\\Nこれが新幹線でした","얘들아, 도착했어. 이게 신칸센이었어","Alright you guys, we made it. That was the bullet train."),
# 1 (O 0:36-1:03)
("O",37.58,42.08,"C","新しい場所、大阪に着きました","새 장소, 오사카에 도착했어요","We have arrived at our new location in Osaka, Japan."),
("O",42.62,47.76,"E","文化と歴史、\\Nそしておいしい食べ物で知られる町です","문화와 역사, 맛있는 음식으로 유명한 도시예요","So this city is known for its culture, history and amazing food."),
("O",47.88,52.24,"E","日本は初めて。\\N何があるのか、すごく楽しみです","일본은 처음이라 무엇이 있을지 너무 기대돼요","This is our first time in Japan and we're really excited..."),
("O",52.62,55.32,"C","昨日の夜に着いたばかりで、\\Nまだあまり見て回れていません","어젯밤에 막 도착해서 아직 많이 못 둘러봤어요","we just got in last night so we didn't get a lot of time to explore."),
("O",55.54,58.82,"C","泊まっているのは、\\Nコリアタウンと呼ばれる地区","묵는 곳은 코리아타운이라 불리는 지역","We're actually living in a section that's actually considered Korea town."),
("O",58.82,62.60,"E","韓国料理の店が多くて、\\N昨日食べたのもおいしかった","한국 음식점이 많고 어제 먹은 것도 맛있었어요","A lot of Korean restaurants in this area, we had one last time, it was really good."),
("O",62.66,68.18,"C","今日は大阪城を見に行きます","오늘은 오사카성을 보러 가요","now we are actually going to go and see the Osaka Castle today."),
# (O 1:18-1:30)
("O",77.88,81.08,"C","まずは、日本のパンケーキを探しに行きます","먼저 일본 팬케이크를 찾으러 가요","So we're going to go look for some Japanese pancakes."),
("O",82.20,84.98,"E","ずっと食べたかったパンケーキ","오래전부터 먹고 싶던 팬케이크","Those pancakes have been on my list for a long long time."),
("O",84.98,89.86,"E","スフレみたいにふわふわで、\\Nすごく背が高いんです","수플레처럼 폭신하고 아주 높아요","They're fluffy souffle type of pancakes, really, really tall."),
# (O 1:42-2:02)
("O",101.12,104.96,"E","電車で行きます。\\N交通カードは昨日、空港で買いました","전철로 가요. 교통카드는 어제 공항에서 샀어요","we're gonna have to go on the train. We did get our train cards yesterday at the airport."),
("O",105.12,109.26,"C","正直、ここの電車には\\N少しおじけづいていました","솔직히 여기 전철이 좀 겁났어요","we were surprised. We were a little intimidated by the train system here,"),
("O",109.82,113.94,"C","でも乗り換え1回で、\\Nちゃんと目的地に着けました","하지만 한 번 갈아타고 목적지에 잘 도착했어요","but we made it to our destination with only one switch of terminal."),
("O",113.94,118.74,"E","初めてだと少しわかりにくいけど、\\N難しくはなかった","처음엔 좀 헷갈리지만 어렵지는 않았어요","and it wasn't very difficult overall a little confusing at times for your first time"),
("O",118.74,123.08,"E","グーグルマップが、\\N行き方をそのまま教えてくれます","구글 지도가 가는 길을 그대로 알려 줘요","the good thing is google maps will basically guide you exactly where you need"),
# (O 2:42-3:00)
("O",162.62,167.16,"C","ここの人は、みんな親切。\\N英語が話せなくても、親切です","여기 사람들은 다 친절해요. 영어를 못 해도 친절해요","everybody's so friendly here. Even if they don't speak English, they've just been friendly."),
("O",167.36,168.70,"E","コナー、「ハロー」は何て言うの？","코너, 「헬로」는 뭐라고 해?","how do you say hello, Connor?"),
("O",170.56,172.16,"B","「こんにちは」！\\N「さようなら」はバイバイ","「곤니치와」! 「사요나라」는 바이바이","Konnichiwa! Sayonara is bye."),
("O",173.56,177.52,"E","「ありがとう」も大事。\\N「ありがとう」は？","「고마워」도 중요해. 「고마워」는?","And then thank you is important, too. What's thank you?"),
("O",178.88,180.24,"B","ありがとう","아리가토","Arigato."),
# (O 4:25-4:51)
("O",265.46,272.08,"E","もうすぐ降りる駅だって、\\Nアプリが教えてくれる。便利","곧 내릴 역이라고 앱이 알려 줘요. 편리해요","App is telling us that it is almost time to get off. That is coming in handy."),
("O",272.08,276.66,"C","車内のアナウンスは英語じゃないから、\\Nほとんどわからない","안내 방송이 영어가 아니라 거의 못 알아들어요","we don't really understand any of the announcements because they're all not in English."),
("O",287.76,290.50,"C","よかった、\\Nこれが降りる駅を教えてくれた","다행이다, 이게 내릴 역을 알려 줬어","Alright, so thankfully this tells us when to get off."),
# 2 (O 6:32-7:12)
("O",388.00,392.18,"E","雨が強くなってきた。\\N傘を持ってきてよかった","비가 세졌어. 우산 가져오길 잘했어","now it is starting to pick up a little bit with the rain i'm glad we brought the umbrellas"),
("O",392.18,396.80,"E","ここのレストランの好きなところ。\\N料理の見本があるんです","여기 식당의 좋은 점. 음식 견본이 있어요","one thing i love about the restaurants a lot of them have like the fake food display"),
("O",399.50,405.88,"C","本物の料理に何か塗ってるのかと\\N思ったけど、全部作り物なんだね","진짜 음식에 뭘 바른 줄 알았는데 다 모형이네","i thought at first maybe they put glue over it and use the real food but i guess it is like totally fake"),
("O",405.88,410.50,"C","見本を作るのは、\\Nひとつの芸術なんだって","모형 만드는 건 하나의 예술이래","and it's a whole art form to actually make the food displays"),
("O",410.50,416.30,"E","でもすごく助かる。\\Nメニューは日本語だけのことが多いから","그래도 큰 도움이 돼요. 메뉴가 일본어뿐인 경우가 많거든요","but it's like really helpful Because a lot of menus are in full Japanese"),
("O",416.30,419.54,"E","しかも翻訳が、すごく面白い","게다가 번역이 엄청 웃겨요","and we discovered that the translations are very very funny"),
("O",419.54,423.50,"C","「目玉の揚げ物」って書いてあって、\\N全然違った","「눈알 튀김」이라고 적혀 있었는데 전혀 아니었어","the one actually said it was like fried eyeballs and it was not fried eyeballs."),
# (O 7:30-8:49)
("O",449.80,452.92,"E","見つけた。\\N「グラム」、カフェとパンケーキ","찾았다. 「그램」, 카페와 팬케이크","Alright, we have found it. Grand Cafe and Pancakes."),
("O",453.32,455.50,"C","みんな好きなもの。\\Nコーヒーとパンケーキ","다들 좋아하는 것. 커피와 팬케이크","Things we can all agree on. Coffee and pancakes."),
("O",455.92,459.88,"E","これがプレミアムの\\N日本のパンケーキ","이게 프리미엄 일본 팬케이크","Okay, so these are the premium Japanese pancakes there."),
("O",461.02,465.32,"E","見て、このふわふわ。\\Nこれを食べに来たの","봐, 이 폭신함. 이걸 먹으러 왔어","Look how fluffy they look though. That's what I want. That's what I came here for."),
("O",466.12,469.76,"E","コナー、見て。\\Nスマイルパンケーキ","코너, 봐. 스마일 팬케이크","Look, Connor. This is the smile pancake."),
("O",472.28,474.38,"E","これで笑顔になれそう？","이거 먹으면 웃게 될 것 같아?","Is it gonna make you smile? Yeah, probably."),
("O",477.54,478.94,"E","あれ、ちょっと待って","어, 잠깐만","Oh, wait a minute."),
("O",479.56,482.58,"E","今日はプレミアムパンケーキが\\Nないって書いてある","오늘은 프리미엄 팬케이크가 없다고 적혀 있어","It says their premium pancakes are not available today."),
("O",483.46,488.48,"C","プレミアムのスマイルパンケーキは、\\N数量限定","프리미엄 스마일 팬케이크는 수량 한정","Oh no, premium smile pancakes are available in limited quantity."),
("O",488.82,491.84,"E","まだあるか、聞いてみよう","아직 있는지 물어보자","Well, let's ask if they still have the premium smile pancakes."),
("O",494.50,498.84,"E","スマイルパンケーキ、まだありますか？\\N数量限定って見たので","스마일 팬케이크 아직 있나요? 수량 한정이라고 봐서요","Do you still have the smile pancakes available? I saw it's limited quantities."),
("O",501.70,502.88,"J","こちらは、大丈夫です","이건 괜찮아요(있어요)","For this, yes."),
("O",503.16,505.86,"E","大丈夫？\\Nよかった、ありがとう","괜찮아요? 다행이다, 고마워요","It's good? Okay, cool, thank you."),
("O",506.02,507.38,"J","英語のメニューです","영어 메뉴예요","English menu."),
("O",509.74,514.94,"J","ご注文が決まったら、\\Nこちらをレジまでお持ちください","주문이 정해지면 이걸 계산대로 가져와 주세요","When you decide to order, please come to the register. In the order."),
("O",515.86,517.42,"E","わかりました。ありがとう","알겠어요. 고마워요","Okay, perfect. Thank you."),
("O",517.96,522.36,"E","注文の仕方を丁寧に教えてくれて、\\N本当にありがたい","주문 방법을 친절히 알려 줘서 정말 고마워요","I really appreciate that she gave me such good instructions on how to order."),
("O",522.36,529.28,"E","日本では、ちょっと戸惑うことも\\Nあるから","일본에서는 좀 헷갈릴 때가 있으니까요","Because sometimes you can get a little confusing in Japan"),
# (O 8:49-9:02)
("O",529.68,531.60,"C","おっと、バランス勝負だ","오, 균형 잡기네","Oh, it's on a balancing act."),
("O",532.34,535.80,"E","プレミアム、食べられた。\\Nありがとう","프리미엄 먹을 수 있게 됐어. 고마워요","We did get the premium. Thank you."),
("O",536.20,541.06,"C","ピサの斜塔みたい。\\N「パンケーキの斜塔」だ","피사의 사탑 같아. 「팬케이크의 사탑」이다","It's like the leaning tower of pizza. The leaning tower of pancakes."),
# (O 9:47-10:12)
("O",587.24,590.96,"E","この子を崩すのが、\\Nすごく悲しい","이 아이를 무너뜨리는 게 너무 슬퍼","And then I'm really really sad that I have to destroy this little guy."),
("O",591.18,594.32,"E","名前をつけようか。\\Nだめ、つけたらもっとつらい。…ピート","이름 붙일까. 안 돼, 붙이면 더 괴로워. …피트","We should name him. No, if we name him, it's worse. Pete."),
("O",596.56,599.48,"C","ごめんな。\\Nいい髪型だな、ピート","미안해. 머리 멋지다, 피트","Sorry, buddy. That's a nice haircut you got there, Pete."),
("O",602.54,606.00,"E","名前をつけたら、\\Nやっぱりもっとつらくなった","이름 붙이니까 역시 더 괴로워졌어","It's gonna feel worse. I know now it does feel worse."),
("O",606.00,609.16,"C","ママが耳に砂糖をのせた。\\N「耳をつけてあげてるの」","엄마가 귀에 설탕을 올렸어. 「귀를 달아 주는 거야」","I think mommy just put some sugar on his ear. I'm giving him ears."),
# (O 11:16-11:41)
("O",679.74,684.90,"C","温かいと思ってたけど、\\N冷たいパンケーキだ","따뜻할 줄 알았는데 차가운 팬케이크네","so i expected those to be hot definitely a cold pancake"),
("O",685.52,691.40,"C","ちょっと驚いた。\\Nでも、なかなかおいしい","좀 놀랐어. 그래도 꽤 맛있어","i'm a little surprised by them it's actually quite good"),
("O",691.40,696.22,"C","見た目で、温かいと思ってた。\\Nふわふわなのはいい","보기엔 따뜻할 줄 알았어. 폭신한 건 좋아","i was expecting hot by the looks of it it's nice fluffy pancakes"),
# (O 12:45-13:26)
("O",764.60,765.52,"E","真ん中を見せて","가운데 보여 줘","Show us the middle."),
("O",768.04,771.62,"C","ほら、ここ。\\Nここにサプライズが入ってる","봐, 여기. 여기에 깜짝 선물이 들어 있어","So see right here? So that's where the little surprise is here."),
("O",771.96,773.44,"E","え、本物の卵？","어, 진짜 달걀이야?","Isn't that an actual egg egg?"),
("O",773.60,777.72,"C","そう、卵が入ってる。\\Nしかも温かい","응, 달걀이 들어 있어. 게다가 따뜻해","Yeah, so there's an egg in there. And it's actually warm."),
("O",778.26,782.46,"C","外は冷たいのに、\\N中に温かい卵が入ってる","겉은 차가운데 안에 따뜻한 달걀이 들어 있어","So that's weird. It's cold on the outside, but it's got like a warm egg on the inside."),
("O",782.54,787.96,"E","卵のクリームか何かだと思ったら、\\N半熟卵みたい","달걀 크림 같은 건 줄 알았는데 반숙 달걀 같아","I was thinking maybe like an egg cream... but it actually looks like a runny egg."),
("O",794.38,796.30,"C","「卵」って、生地に入ってるって\\N意味じゃなかったんだ","「달걀」이 반죽에 들어 있다는 뜻이 아니었구나","When they say egg, they weren't just saying fluffed up with egg."),
("O",801.92,806.04,"C","これはすごい。\\Nこの店に来たかいがあった","이건 대단해. 이 가게에 온 보람이 있었어","Okay, now that is amazing. That was worth coming to this place for."),
# (O 15:02-15:29)
("O",907.42,911.56,"C","この朝ごはんは大成功","이 아침 식사는 대성공","So I'd say this is a hit. Overall I'd say this breakfast is a winner."),
("O",911.56,917.72,"E","全部で6090円。\\N39ドルくらいです","전부 6090엔. 39달러 정도예요","this meal was 6,090 yen which is equivalent of 39 US dollars"),
("O",917.72,927.98,"E","アメリカなら60ドルくらいかな。\\Nいいお値段だと思う","미국이라면 60달러쯤일까. 괜찮은 가격이에요","probably 60 bucks... I think a pretty good deal for me"),
("O",927.98,933.98,"C","次は、お城を見に行きます","다음은 성을 보러 가요","we'll get to exploring the castle"),
# 3 (O 19:48-20:10)
("O",1186.50,1195.72,"C","全部、鉄と鋲でできた門。\\Nこんなに大きな蝶番は初めて見た","전부 철과 리벳으로 된 문. 이렇게 큰 경첩은 처음 봐","Here is a gate. Looks like it's all steel and rivets... biggest hinges I've ever seen."),
("O",1196.98,1204.64,"E","お城の門をくぐると、\\N丘の上にお城が見える","성문을 지나면 언덕 위에 성이 보여","And right as you enter through the castle doors, you see the castle at the hill."),
("O",1204.64,1209.50,"C","ほら、ずっと上だよ、コナー。\\Nあそこにも、また堀がある","봐, 저 위야, 코너. 저기에도 또 해자가 있어","See it's way up there on the hill, Connor. But look, there's another moat."),
# (O 20:27-20:55)
("O",1227.12,1234.10,"E","ローガンが壁の上に登ってる。\\N堀の壁に登れるみたい","로건이 벽 위에 올라갔어. 해자 벽에 올라갈 수 있나 봐","Logan's climbing on top of the wall over here..."),
("O",1235.38,1240.44,"C","昔はここで、弓矢で\\Nお城を守っていたんだろうな","옛날엔 여기서 활로 성을 지켰겠지","They would have stayed up here with like bows and arrows to protect the castle"),
("O",1244.64,1247.64,"E","ローガン、傘で\\Nお城を守る準備はできた？","로건, 우산으로 성 지킬 준비 됐어?","You got your umbrella ready to protect the castle Logan?"),
("O",1249.64,1254.40,"C","上がっておいで。\\Nお城の見張りになった気分を味わおう","올라와. 성 파수꾼이 된 기분을 느껴 보자","come on up see what it would have been like to be a guard of the castle"),
# (O 23:13-23:30)
("O",1393.64,1394.92,"E","人の20分の1","사람의 20분의 1","One-twentieth of a person."),
("O",1395.54,1399.66,"C","この馬に乗って戦いたい？\\Nどの兵士になる？","이 말을 타고 싸우고 싶어? 어느 병사가 될래?","Would you like to be fighting back then on one of these horses? Which soldier would you be?"),
("O",1401.64,1403.86,"B","侍のひとりになる","사무라이 중 하나가 될래","I would be one of the samurais."),
("O",1406.20,1407.98,"B","赤い侍がいい","빨간 사무라이가 좋아","I would be a red samurai."),
# (O 24:27-25:12)
("O",1463.00,1469.76,"E","特にコナーは、\\N博物館の展示が気に入ったよね","특히 코너는 박물관 전시가 마음에 들었지","Connor actually really enjoyed the museum portion of it didn't you Connor?"),
("O",1469.96,1471.58,"E","どこがよかった？","어디가 좋았어?","what do you like about it?"),
("O",1471.92,1481.02,"B","この城を作った人の一生を、\\N生まれてから死ぬまで話してくれるところ","이 성을 만든 사람의 일생을 태어나서 죽을 때까지 이야기해 주는 게","I like how it's like the story telling you the story like from birth to death for the one of the person that created this"),
("O",1488.80,1491.62,"C","すごく貧しい家に生まれたんだよね。\\N名前は？","아주 가난하게 태어났지. 이름은?","So he was born very poor. What was his name?"),
("O",1491.62,1492.54,"B","秀吉","히데요시","Hideyoshi"),
("O",1493.12,1499.74,"E","人々をひとつにまとめることに、\\N一生をささげたんだって","사람들을 하나로 모으는 데 일생을 바쳤대","his life was spent and dedicated to unite the people"),
("O",1505.64,1512.26,"E","国のばらばらの地域を、\\Nひとつにまとめた。すごく面白かった","나라의 흩어진 지역을 하나로 모았어. 정말 재밌었어","the different areas of the country to one place. Yeah, it's really really cool"),
# (O 27:08-28:30)
("O",1626.58,1633.34,"C","初めての日本の自動販売機。\\N駅に着く前に、子どもたちが「飲み物！」","처음 써 보는 일본 자판기. 역에 가기 전에 아이들이 「음료!」","The first time using a Japanese vending machine... the kids said we need a drink"),
("O",1640.06,1643.90,"C","千円入れた。\\Nローガン、飲み物を押して","천 엔 넣었어. 로건, 음료 눌러","Okay now a thousand yen and push a drink Logan"),
("O",1648.92,1653.00,"C","はい、出てきた。簡単だった","자, 나왔다. 쉬웠어","Okay, well there you have it that was easy,"),
("O",1653.00,1659.12,"E","おつりボタンを押す前に、\\N何本か買えばよかったね","거스름돈 버튼 누르기 전에 여러 개 살걸","I think we should have gotten more before we did the change... before you hit the coin button."),
("O",1659.12,1663.38,"C","でも、小銭も使えるって書いてある","그래도 동전도 된다고 적혀 있어","But it also says use your coins here. Okay, so we can use coins."),
("O",1664.08,1669.18,"E","どこ？　ここ？　違う。\\Nここ？","어디? 여기? 아니야. 여기?","Where? Here maybe? No. In here?"),
("O",1671.10,1674.86,"E","このビタミンのを試してみる","이 비타민 같은 걸 마셔 볼래","Maybe I'm going to try this vitamin thing."),
("O",1680.20,1682.08,"E","先におつりを返して、ってことね","먼저 거스름돈을 돌려줘야 하나 봐","Give us our change back first, I guess."),
("O",1689.32,1691.96,"C","ビタミンウォーターみたいなもの？","비타민 워터 같은 거?","Vitamin type of water thing. Some kind of Japanese vitamin water, okay"),
("O",1697.95,1703.99,"E","すごくさっぱり。チェリーレモン味。\\N甘すぎなくて、おいしい","정말 상쾌해. 체리 레몬 맛. 너무 달지 않고 맛있어","Really refreshing, this is a cherry lemon flavor. Super good, not extremely sweet"),
("O",1708.03,1709.55,"C","ローガンはレモンティー？\\Nおいしい？","로건은 레몬티? 맛있어?","You got a lemon tea Logan? Is it good?"),
# (O 29:43-30:10)
("O",1783.11,1786.97,"C","電車がぎゅうぎゅうだ。\\Nどこかで立つしかない","전철이 꽉 찼어. 어디서든 서 있어야겠어","Our train is super packed where it's going to be standing up somewhere here."),
("O",1787.97,1794.65,"E","誰か降りてくれるといいけど","누가 좀 내려 주면 좋을 텐데","Hopefully people get off though."),
("O",1800.94,1807.38,"C","すごく混んだ電車に乗れた。\\Nでも楽しい","엄청 붐비는 전철에 탔어. 그래도 재밌어","Alright we made it on the very very crowded train. It is fun though."),
("O",1807.38,1810.58,"C","泊まっているコリアタウンに\\N戻ってきました","묵고 있는 코리아타운으로 돌아왔어요","back in our neighborhood where we're staying back in Koreatown."),
# 4 (O 31:25-32:35)
("O",1891.40,1897.92,"E","靴は脱ぐ。もちろん、靴は禁止。\\Nちゃんと札で知らせてくれる","신발은 벗어요. 당연히 신발 금지. 표시로 알려 줘요","And take off our shoes. Yes, of course, no shoes. And they remind you..."),
("O",1898.46,1903.02,"C","玄関のすぐ横に、\\N日本で有名なものがあります","현관 바로 옆에 일본에서 유명한 게 있어요","So right off the main door we have something Japan is very famous for."),
("O",1903.50,1906.62,"E","ビデ付きのトイレ。\\Nローガンは、もうよく知ってる","비데 화장실. 로건은 이미 잘 알아","Bidet toilets. Logan knows all about that."),
("O",1906.94,1911.44,"C","着いてすぐ体験したんだよな。\\N流そうとして、どうなった？","도착하자마자 경험했지. 물 내리려다 어떻게 됐어?","Logan experienced the bidet toilet right off the bat... You're trying to flush it, what happened?"),
("O",1912.24,1915.68,"B","全身に水がかかった。\\N床がびしょびしょになった","온몸에 물이 뿌려졌어. 바닥이 다 젖었어","It sprayed my whole body. I made a big mess all over the floor."),
("O",1926.56,1930.98,"E","流すボタンだと思って押したの。\\N流すのは、こっち","물 내리는 버튼인 줄 알고 눌렀어. 물 내리는 건 이거","So he turned it on thinking it was the flusher. But right here is actually the flush."),
("O",1932.10,1941.64,"C","流すと、上の小さな手洗いから\\N水が出る。ここで手が洗える","물을 내리면 위의 작은 세면대에서 물이 나와. 여기서 손을 씻을 수 있어","And when you flush... actually you have a little sink on top. So you can wash your hands"),
("O",1944.96,1949.36,"E","でも気に入ってるの。\\N温かいお湯が出るんです","그래도 마음에 들어요. 따뜻한 물이 나와요","But the cool thing about this is we've actually been enjoying it. It actually sprays warm water."),
("O",1950.04,1955.96,"E","本当に温かくて、\\N実はすごくいい","정말 따뜻해서 사실 아주 좋아요","Yeah, really nice warm water. That's actually nice."),
# (O 35:04-35:08)
("O",2103.20,2108.80,"E","次は東京。\\N向こうの部屋は、ずっと狭くなります","다음은 도쿄. 거기 방은 훨씬 좁아져요","we're going to Tokyo next and our place is going to be a lot smaller."),
# 5 (O 37:21-37:33)
("O",2241.40,2245.00,"C","速くて、簡単で、効率的","빠르고 쉽고 효율적이에요","Quick easy and efficient"),
("O",2245.00,2252.24,"C","地下鉄で好きなところは、\\N地下にお店やレストランがたくさんあること","지하철에서 좋은 건 지하에 가게와 식당이 많다는 거예요","the one thing I love about the metro system... they have the most amazing malls and restaurants"),
# (O 38:39-40:20)
("O",2315.00,2318.50,"C","移動はすごく簡単。\\Nここまで一度も迷ってない","이동이 아주 쉬워요. 지금까지 한 번도 안 헤맸어요","very easy to navigate. So far we haven't got lost."),
("O",2318.50,2326.70,"E","着きました。\\Nお寿司の写真がいっぱい。期待できそう","도착했어요. 초밥 사진이 가득. 기대돼요","So we're here. This restaurant looks great. I can already see lots of pictures of sushi."),
("O",2335.38,2340.00,"C","秘密の個室に入ります","비밀 방에 들어가요","We're going into our secret compartment."),
("O",2340.00,2350.98,"E","店員さんが説明してくれました。\\N注文は全部画面で、料理はレーンで届く","점원이 설명해 줬어요. 주문은 전부 화면으로, 음식은 레인으로 와요","He with a little rundown basically we order everything on the screen and it's going to come through this conveyor belt"),
("O",2350.98,2359.40,"E","「レーンに荷物を置かないで」","「레인에 짐을 두지 마세요」","Don't put your baggage or stuffs on the lane."),
("O",2364.00,2372.90,"E","ポン酢、しょうゆ、緑茶。\\Nお湯もここから出ます","폰즈, 간장, 녹차. 뜨거운 물도 여기서 나와요","we have ponzu, we have soy sauce, we have green tea... hot water right there"),
("O",2376.76,2381.22,"C","英語の画面があるから、\\N言葉が通じなくても簡単","영어 화면이 있어서 말이 안 통해도 쉬워요","it makes it easy with the language barrier having it in English pad."),
("O",2381.22,2394.10,"E","今日のおすすめ。\\Nいちばん新鮮な魚が出ています","오늘의 추천. 가장 신선한 생선이 나와 있어요","today's recommendations... the freshest and the best"),
("O",2394.10,2401.54,"E","生が苦手なら、炙りもある。\\Nコナーはそっちかな","날것이 싫으면 구운 것도 있어. 코너는 그쪽일까","seared sushi if you don't want the raw stuff... Connor might do."),
("O",2402.48,2407.36,"E","サーモンのチーズのせもある","연어 치즈 얹은 것도 있어","You can get salmon with cheese. Oh, salmon with cheese, sign me in."),
("O",2414.88,2421.00,"E","コナーがお寿司に乗り気でよかった","코너가 초밥에 관심 있어서 다행이에요","It's good that he's excited about it, though."),
# (O 40:32-41:13)
("O",2430.40,2434.30,"E","一緒に食べよう。乾杯しようか","같이 먹자. 건배할까","Yeah, I'll try it with you. We'll do a little cheers, okay?"),
("O",2435.34,2443.82,"E","お箸がちょっと怖いみたい。\\N練習用のお箸がいるね","젓가락이 좀 무서운가 봐. 연습용 젓가락이 필요하겠어","He's a little intimidated by the chopsticks... we need to get like the training chopsticks"),
("O",2443.82,2451.04,"E","しょうゆに少しつけて。\\Nそう、上手","간장에 조금 찍어. 그래, 잘하네","dip it in the little bit in the soy sauce... Doing good."),
("O",2459.16,2468.14,"C","ローガンの抹茶を作ります。\\N粉をスプーン1、2杯入れて","로건의 말차를 만들어요. 가루를 한두 스푼 넣고","We're gonna make Logan's matcha... one to two teaspoons of the powder"),
("O",2468.14,2470.64,"C","お湯は、テーブルのここから","뜨거운 물은 테이블의 여기서","You have your hot water dispenser right here at the table"),
# (O 41:44-42:20)
("O",2500.00,2506.46,"E","マグロ？サーモン？\\Nアボカドとサーモン","참치? 연어? 아보카도와 연어","or salmon? Salmon! ... Avocado and salmon."),
("O",2509.10,2513.44,"E","すごくおいしい。\\Nアメリカで食べたどれよりもおいしい","정말 맛있어. 미국에서 먹은 어떤 것보다 맛있어","That's amazing. It's so good. Way better than anything I've had in the U.S."),
("O",2514.24,2519.54,"E","魚がすごく新鮮","생선이 정말 신선해","and the fish itself it just tastes so fresh."),
("O",2519.54,2528.32,"E","ひとつ気になるのは、\\Nわさびはないのかな","하나 궁금한 건, 와사비는 없나","The one thing I'm wondering is do they do wasabi here?"),
("O",2532.40,2540.32,"C","これは？　しょうが。\\Nしょうがとわさびはアメリカでは普通","이건? 생강. 생강이랑 와사비는 미국에선 보통이야","That's ginger... that's normal in America to get some ginger and wasabi."),
# (O 42:44-43:25)
("O",2564.16,2571.36,"E","コナー、日本で初めてのお寿司。\\Nどう？","코너, 일본에서 첫 초밥. 어때?","Okay Connors first sushi in Japan did you like it?"),
("O",2579.88,2584.04,"E","指をパチン。\\Nコナー語で「おいしい」","손가락을 튕겼어. 코너 말로 「맛있다」야","He gave a little finger snap. That's Connors speak for I like it."),
("O",2587.66,2590.70,"C","何か届いたぞ","뭔가 도착했어","We just had an arrival"),
("O",2596.78,2605.12,"E","エビのガーリックしょうゆ焼き。\\Nクリスは生のお寿司が苦手なの","새우 마늘 간장 구이. 크리스는 날 초밥을 별로 안 좋아해요","these are prawns with garlic soy glazed... Chris is not the biggest raw sushi person"),
# (O 44:54-45:16)
("O",2690.00,2696.00,"C","うなぎのタレが好きなんだけど、\\N日本にはないのかな","장어 소스를 좋아하는데 일본엔 없나","I like stuff with eel sauce. Is that nothing, not real thing that they do in Japan?"),
("O",2698.74,2702.82,"E","辛いのとか、カリカリのとか、\\Nここにはないみたい","매운 거나 바삭한 거는 여기 없나 봐","They don't do like the spicies or the crunchies or it's not a thing here."),
("O",2703.44,2712.36,"E","お寿司を、そのままの味で食べる。\\N魚の味を、ソースで隠さない","초밥을 그대로 먹어요. 생선 맛을 소스로 가리지 않아요","I think they keep their sushi very pure. You want to taste the seafood."),
("O",2712.36,2715.54,"C","それは、俺たち\\Nクレイジーなアメリカ人の好み","그건 우리 미친 미국인들 취향","That's us crazy Americans that... Which we do really like."),
("O",2716.18,2720.98,"E","日本では、\\N同じお寿司を期待しないでね","일본에선 같은 초밥을 기대하지 마세요","if you come to Japan, don't expect the same type of sushi."),
# (O 48:19-48:50)
("O",2896.42,2903.64,"E","正直、好きじゃない。\\Nすごく食べにくい","솔직히 별로야. 너무 먹기 힘들어","I would say it's not my favorite. It's too messy... It's very messy to eat."),
("O",2903.82,2911.16,"C","皮がついてるみたい。\\N魚の皮は苦手","껍질이 붙어 있는 것 같아. 생선 껍질은 별로야","it still has the skin on it too. I'm not a fan of the fish skin personally."),
("O",2911.16,2914.50,"C","生は苦手。\\Nカリカリなら好き","날것은 별로. 바삭하면 좋아","I'm not a fan of it raw. If it's crispy I like it."),
("O",2914.50,2919.24,"E","ローガン、「まもなく到着」って\\N書いてある","로건, 「곧 도착」이라고 적혀 있어","It does say it Logan. It says we will be arriving shortly."),
("O",2923.90,2925.38,"E","コナー、チキンが来たよ","코너, 치킨 왔어","Alright Karna you get to get your chicken though."),
("O",2926.28,2929.86,"B","言ったでしょ","내가 말했잖아","I told you."),
# (O 51:39-51:58)
("O",3100.42,3112.44,"E","全部で6065円。\\N39ドルくらい","전부 6065엔. 39달러 정도","6065 yen which is about 39 u.s dollars"),
("O",3112.44,3115.00,"E","この質のお寿司で、すごくいい値段","이 품질 초밥에 정말 좋은 가격","overall really good prices for the quality sushi that we got"),
# (O 52:23-52:56)
("O",3139.00,3149.26,"C","大阪の印象。自転車がいる。\\N車じゃなくて、自転車に気をつける","오사카의 인상. 자전거다. 차가 아니라 자전거를 조심해요","Overall impression of Osaka... instead of getting hit by cars"),
("O",3149.26,3156.18,"C","何百万人も住む都会なのに、\\N全然落ち着かない感じがしない","수백만이 사는 도시인데 전혀 불안하지 않아요","We haven't felt like you know uneasy at all like even though it's a city with millions of people."),
("O",3156.18,3162.30,"E","すごく穏やかなんです","정말 평온해요","There's just something very calming about it."),
("O",3162.30,3168.18,"C","人が大勢いても、穏やかに歩ける","사람이 많아도 편하게 걸을 수 있어요","Even when there's millions of people they make it very calming... to wander around the city"),
("O",3168.18,3173.56,"E","あと数日、大阪を見て回れるのが\\N楽しみです","며칠 더 오사카를 둘러볼 수 있어서 기대돼요","So we're excited that we're gonna have another few days here to explore"),
# 6 (T 0:30-0:53)
("T",30.21,35.51,"E","今日は、大阪から東京へ移動します","오늘은 오사카에서 도쿄로 이동해요","Today, we are moving from Osaka, Japan to Tokyo."),
("T",35.89,42.97,"C","新幹線で行きます。\\N世界でいちばん速い列車のひとつ","신칸센으로 가요. 세계에서 가장 빠른 열차 중 하나","by bullet train. So I'm excited to go on one of the fastest trains in the world."),
("T",43.09,46.75,"E","東京まで2時間半くらい。\\Nすごく速い","도쿄까지 2시간 반 정도. 정말 빨라요","It's about a two and a half hour bullet train to Tokyo."),
("T",47.17,51.39,"E","でもまず、\\N新幹線が出る駅まで行かないと","하지만 먼저 신칸센이 출발하는 역까지 가야 해요","But first we have to get to a train station where the bullet trains take from."),
("T",51.39,55.35,"C","エスカレーターがあるといいな。\\N前は階段で運んで大変だった","에스컬레이터가 있으면 좋겠다. 전엔 계단으로 옮겨서 힘들었어","I'm hoping I can find an escalator. Last time I had to carry the bags... up and down some stairs."),
# (T 1:04-2:08)
("T",64.00,73.46,"E","鶴橋駅に向かいます。\\Nコリアタウンの中にある駅","쓰루하시역으로 가요. 코리아타운 안에 있는 역","we are going to the Tsuruhashi station which is over here in Koreatown"),
("T",73.46,81.98,"E","これが、1年間旅する\\N私たちの荷物の全部","이게 1년 동안 여행하는 우리 짐 전부","this is all of our luggage that we're traveling with for an entire year"),
("T",88.48,95.18,"C","探したけど、下りのエレベーターも\\Nエスカレーターもない","찾아봤는데 내려가는 엘리베이터도 에스컬레이터도 없어","So we searched and searched and I couldn't find an elevator or escalator down"),
("T",95.18,101.92,"C","重い荷物を担いで下ります。\\N幸運を祈ってて","무거운 짐을 메고 내려가요. 행운을 빌어 줘","so I have to carry my very heavy bags down here so wish me luck."),
("T",102.02,103.36,"C","これで45キロ","이걸로 45킬로","Alright this is 100 pounds right here."),
("T",108.96,113.16,"C","太り気味の体に、\\N腰痛もあるのに","과체중 몸에 허리도 아픈데","Is this my overweight body? And bad back."),
("T",115.24,120.52,"E","ひとつずつ運んでって言ったのに。\\N聞いてくれる？　まさか","하나씩 옮기라고 했는데. 들어줄까? 설마","I mean, I did suggest you do it one at a time, but can you listen? No."),
("T",125.67,130.01,"E","やった、下りられた","해냈다, 내려왔어","Alright, you made it."),
# (T 3:09-3:32)
("T",185.00,191.50,"C","ここで乗り換え。\\N次の地下鉄へ","여기서 갈아타기. 다음 지하철로","So now we get on to a second metro train"),
("T",191.50,196.30,"E","次は赤い線。\\Nさっきはピンクの線だった","다음은 빨간 선. 아까는 분홍 선이었어","So now we have to go to the red line. We were just on the pink line."),
("T",196.50,205.48,"C","色で分かれていてわかりやすい。\\Nグーグルマップも教えてくれる","색으로 나뉘어 있어 알기 쉬워요. 구글 지도도 알려 줘요","It's pretty easy to navigate... color coded... Google Maps."),
("T",205.48,212.34,"E","これが新幹線に乗る前の\\N最後の地下鉄","이게 신칸센 타기 전 마지막 지하철","that will be our final metro for right now and that will take us to our bullet train."),
# (T 4:14-4:31)
("T",252.28,263.84,"E","日本の地下鉄や電車には、\\N少しおじけづいていました","일본 지하철이나 전철이 좀 겁났었어요","I was a little intimidated by all the metros and train systems here in Japan"),
("T",263.84,265.96,"E","でも、ここまで一度も迷ってない","하지만 지금까지 한 번도 안 헤맸어요","But so far we've never been lost"),
("T",265.96,270.72,"C","意外と簡単。\\Nでも今日は、今までで一番混んでる","의외로 쉬워요. 그런데 오늘이 지금까지 가장 붐벼요","Actually seems pretty easy. Today's actually been the busiest that the trains have been"),
("T",270.72,274.06,"E","よりによって、\\N荷物を引きずってる日にね","하필 짐을 끌고 다니는 날에","Yeah, of course when we have our luggage to drag along with us"),
# (T 4:42-5:07)
("T",280.37,286.39,"C","でも新幹線は座れる。\\N予約してあるから","그래도 신칸센은 앉을 수 있어요. 예약했으니까","But we are going to have seats on the bullet train. Because we're reserved"),
("T",286.67,291.45,"E","数日前に、駅で\\Nきっぷを買いました","며칠 전에 역에서 표를 샀어요","We only bought our tickets a couple days ago at the train station."),
("T",295.73,306.15,"E","予約すると、\\N大きな荷物の置き場も確保できます","예약하면 큰 짐 둘 자리도 확보돼요","make sure that we reserved our tickets. That way we have space for our luggage."),
# 7 (T 6:08-6:33)
("T",369.20,375.40,"E","新幹線は、\\N「シンカンセン」っていうの？","신칸센은 「신칸센」이라고 해?","So the bullet train is called the Shinkansen line?"),
("T",375.68,384.66,"C","まず、この駅を出る。\\N新幹線は、いつものカードとは別","먼저 이 역을 나가요. 신칸센은 늘 쓰는 카드와 별개","first we have to scan out of the station because the bullet train is completely separate from the typical cards."),
("T",387.16,393.28,"E","このカードは、電車も地下鉄も使える。\\N新幹線だけは別","이 카드는 전철도 지하철도 돼요. 신칸센만 별도","these cards typically work everywhere, the trains, the metros, except the bullet trains."),
# (T 6:57-9:05)
("T",417.10,419.78,"C","大きな看板。\\N場所はここで合ってる","큰 간판. 장소는 여기가 맞아","okay really giant sign so we're definitely at the right place"),
("T",420.30,426.56,"E","なんで、指定席のきっぷと普通のきっぷが\\N別々なんだろう","왜 지정석 표랑 일반 표가 따로일까","i don't know why we have like we get separate tickets for our reserve seats and then the general admission tickets"),
("T",427.76,429.98,"E","今、ちょっとややこしい","지금 좀 헷갈려","yeah it's a little confusing right now"),
("T",429.98,438.22,"C","カードみたいにタッチする？\\Nタッチするところがない","카드처럼 찍어? 찍는 데가 없어","do you scan these just like we scan a card or doesn't really have a scan thing"),
("T",438.22,445.45,"C","わからない。\\N周りの人を見てみよう","모르겠다. 주변 사람들을 보자","i don't know we'll watch other people"),
("T",445.45,450.35,"E","きっぷを吸い込むタイプの改札だね","표를 빨아들이는 개찰구네","these are different types that actually eat your ticket"),
("T",450.93,455.89,"C","どっちを入れる？\\N乗車券のほうだと思う","어느 걸 넣어? 승차권 쪽인 것 같아","Do you understand which one we're putting in? ... I'm thinking it's the fair ticket."),
("T",456.53,457.93,"E","黄色の差し込み口に入れて","노란 투입구에 넣어","Put it in the little yellow slot."),
("T",464.11,466.63,"E","開かない？\\Nコナーのところが開かなかった","안 열려? 코너 쪽이 안 열렸어","Did it not work? It didn't open for Connor."),
("T",468.01,469.37,"C","場所が違ったのかも","장소가 틀렸나 봐","It might have been the wrong place."),
("T",484.53,487.80,"C","優先の列なのかな","우선 줄인가","maybe that's the priority line"),
("T",496.91,500.91,"C","9時57分。間に合うといいけど。\\Nひとりずつ","9시 57분. 늦지 않으면 좋겠다. 한 명씩","957 hopefully we can make it through here. Okay one at a time"),
("T",505.53,513.65,"E","合ってるか確かめよう。\\N指定席券と…","맞는지 확인하자. 지정석권이랑…","Okay let's make sure we got the right ones... for the reserve ticket and the"),
("T",514.95,519.05,"E","どれがどれ？\\Nこの2枚を一緒に？","어느 게 어느 거야? 이 두 장을 같이?","do you know which is which okay okay these two together"),
("T",521.03,524.53,"C","きっぷは向こうから出てきた？","표가 반대쪽으로 나왔어?","okay did your tickets come out the other side yeah they did"),
("T",524.53,536.41,"C","2枚とも入れるんだ。\\N指定席券と乗車券","두 장 다 넣는 거구나. 지정석권과 승차권","you have to put both tickets in... we had a reserve seat and we had a regular ticket"),
("T",536.41,542.85,"C","2枚同時に入れる。\\N予約しなくても乗れるのに、変だな","두 장을 동시에 넣어. 예약 안 해도 탈 수 있는데 이상하네","so you have to put those in the same time which doesn't make sense because you don't have to reserve a seat technically"),
("T",542.85,546.69,"C","指定席なら、2枚一緒。\\N通れました","지정석이면 두 장 같이. 통과했어요","so I guess if you have a reserve seat you got to put them in the same time we made it through"),
# 8 (T 10:10-10:25)
("T",610.34,617.52,"C","列車が来た。\\N先頭がかっこよかった","열차가 왔어. 앞모습이 멋졌어","Our train is here. That looked really cool in the front... this train is beautiful."),
("T",625.07,628.59,"E","広くて、\\N足元もゆったり","넓고 발밑도 여유로워요","Nice and spacious. A lot of leg room."),
# (T 10:42-11:13)
("T",640.91,646.27,"E","すごくきれい。\\N今のところ、すごくなめらか","정말 깨끗해요. 지금까지 아주 부드러워요","Really clean. And so far, pretty smooth."),
("T",646.27,654.31,"C","最高速度に達しました。\\N時速300キロ","최고 속도에 도달했어요. 시속 300킬로","We are up to top speed now, which is 185 miles per hour, or 300 kilometers an hour."),
("T",654.95,661.31,"C","そんなに速く感じないけど、\\N窓の外を見ると速い","그렇게 빠르게 느껴지진 않지만 창밖을 보면 빨라요","So it doesn't feel like we're going that fast, but it's definitely going fast when you look out the window"),
("T",664.11,669.41,"E","どう？　すごく速い？","어때? 엄청 빨라?","What do you think buddy? It's really fast?"),
("T",669.47,673.37,"E","私はなぜか速く感じない。\\Nでもすごくなめらか","난 왠지 빠르게 안 느껴져. 그래도 정말 부드러워","I don't know, it doesn't feel so fast to me for some reason, but it's very smooth."),
# (T 15:17-15:43)
("T",919.52,923.86,"E","乗って1時間。\\Nあと1時間半","탄 지 1시간. 앞으로 1시간 반","We have been on the train for about an hour now an hour and a half to go"),
("T",927.54,934.58,"E","あっという間。たぶん今までで\\Nいちばん快適な列車。すごく清潔","눈 깜짝할 새. 아마 지금까지 가장 편한 열차. 정말 깨끗해","Felt like a short amount of time... probably the most comfortable train I have ever been on"),
("T",934.58,941.40,"E","無料のWi-Fiもあります","무료 와이파이도 있어요","There is free Wi-Fi"),
# 9 (T 16:58-17:16)
("T",1023.79,1028.31,"E","速くて、効率的で、清潔で、\\Nすごくなめらかだった","빠르고 효율적이고 깨끗하고 정말 부드러웠어","It was quick, efficient, clean, really smooth ride."),
("T",1028.49,1035.17,"E","全然速く感じなかった。\\N私も何度かうとうとした","전혀 빠르게 느껴지지 않았어. 나도 몇 번 졸았어","It didn't even feel all that fast. Yeah, I even dozed off a couple times too."),
# (T 17:51-18:28)
("T",1067.00,1071.94,"C","でも、ものすごく速く着く","하지만 엄청 빨리 도착해요","but you do get here at speedy, speedy time"),
("T",1072.68,1081.08,"E","4人で44140円。大人2人、子ども2人。\\N子どもは大人の半額","4명에 44140엔. 어른 2, 아이 2. 아이는 어른 반값","So it was 44,140 yen for the four of us. That's two adults, two kids. The kids are half"),
("T",1081.08,1086.72,"E","4人で約283ドル","4명에 약 283달러","which brings it down to about $283 for the four of us."),
("T",1087.04,1090.18,"E","飛行機より安いよね？","비행기보다 싸지?","So still cheaper than flying if we were to fly, right?"),
("T",1090.58,1101.78,"C","実は飛行機のほうが安かった。\\Nでも空港は町から1時間離れてる","사실 비행기가 더 쌌어. 하지만 공항이 도시에서 1시간 떨어져 있어","Technically, the flights were cheaper... the airports are kind far outside the city"),
("T",1101.86,1108.62,"E","便利で、手ごろで、快適。\\N新幹線の勝ちね","편하고 적당하고 쾌적해. 신칸센의 승리네","more convenient and decent price and comfortable. I'd say the bullet trains are a win."),
]

# --- v1b: 화면 기준 검사(check_subs_shown)에서 「말했는데 자막 없음」으로 나온 곳 보충
C += [
("O",89.88,91.76,"C","子どもたちは向こうで跳ね回ってる","아이들은 저쪽에서 뛰어다녀요","Kids are just like over there popping around a bit."),
("O",123.08,126.78,"E","今いる場所と行きたい場所を入れれば、\\Nいちばんいい行き方を教えてくれる","현재 위치와 가고 싶은 곳을 넣으면 가장 좋은 길을 알려 줘요","as long as you put in where you're at and where you want to go it will tell you the route."),
("O",180.62,181.34,"E","そう、よくできました","그래, 잘했어","There you go. Good job."),
("O",276.74,278.24,"C","まあ、それは当然だよね","뭐, 그건 당연하지","Just to be expected here."),
("O",283.94,285.84,"B","ここがぼくの入り口だと思う","여기가 내 입구인 것 같아","I think this is for my entrance."),
("O",396.80,399.40,"E","あそこの店なんて、\\N見本がこんなにたくさん","저기 가게는 견본이 이렇게나 많아","and if you can see over there a restaurant has just like so much"),
("O",423.58,425.98,"C","ここにも、きれいなのがある","여기에도 예쁜 게 있어","So here we got some pretty stuff right here"),
("O",430.86,434.50,"E","でも行きたいのは、一日中\\N朝ごはんが食べられる店","그래도 가고 싶은 건 하루 종일 아침을 먹을 수 있는 가게","But we're trying to go to the all-day breakfast place"),
("O",434.50,439.00,"E","子どもたちが行きたがってたから。\\N見て、この卵、完璧","아이들이 가고 싶어 했거든. 봐, 이 달걀 완벽해","cuz that's what the kids really wanted look at the egg how perfect It looks"),
("O",470.00,472.10,"E","これがいいんじゃない？\\Nほら","이게 좋지 않아? 자","I think that's what you need, right? Come on."),
("O",474.44,477.12,"C","チョコ味もある。\\N見て、触らないで","초코 맛도 있어. 봐, 만지지 마","They have a chocolate version. Look at this, you don't have to touch it."),
("O",609.96,611.80,"E","ピートに、やさしくしてるの","피트에게 살살 하는 중이야","Okay, I'm trying to be gentle with me."),
("O",676.06,679.24,"C","おいしそう。食べてみよう","맛있어 보여. 먹어 보자","looks really good let's see"),
("O",696.22,700.66,"C","これはデザートの\\Nパンケーキって感じかな","이건 디저트 팬케이크 같은 느낌","this is definitely should be more of a dessert type of pancake"),
("O",789.16,793.36,"C","間違いなく半熟卵。\\Nこれはサプライズ","틀림없이 반숙 달걀. 이건 깜짝이야","that is definitely a normal running egg there. So that's a surprise."),
("O",806.32,808.24,"C","ママにもひと口あげよう","엄마한테도 한 입 주자","And we're gonna give mom a bite here too."),
("O",898.00,907.02,"E","卵のパンケーキを食べてみて。\\N卵が好きなのね。ほおばってる","달걀 팬케이크 먹어 봐. 달걀 좋아하는구나. 입에 가득","try the egg pancake. You like eggs. You got a mouthful there."),
("O",1240.84,1242.84,"C","ピュン、ピュン、ピュン","피융, 피융, 피융","pew pew pew"),
("O",1247.98,1249.02,"B","庭にもある","마당에도 있어","I have one in the yard"),
("O",1404.32,1406.20,"C","みんな侍だよ","다 사무라이야","Yeah, well they all are like samurai."),
("O",1408.00,1411.08,"C","馬に乗るのがいいんじゃない？\\Nいちばんいい場所だよ","말 타는 게 좋지 않아? 제일 좋은 자리야","Yeah, would you be on a horse probably? That would be the best place to be, no?"),
("O",1481.02,1486.96,"C","サルのような顔で生まれたって、\\N展示に書いてあった","원숭이 같은 얼굴로 태어났다고 전시에 적혀 있었어","He was actually born with the face of a monkey. That is what they said in the thing"),
("O",1486.96,1488.80,"E","見た目は普通だったけど","보기엔 평범했는데","He looked rather normal to me"),
("O",1503.36,1505.64,"B","全部の国が…","모든 나라가…","All the countries although"),
("O",1634.00,1636.24,"C","お金を入れる","돈을 넣고","insert our money"),
("O",1669.62,1671.10,"E","これ？","이거?","This thing?"),
("O",1676.62,1677.56,"E","コナーも選んで","코너도 골라","Then Connor, you choose something."),
("O",1682.88,1684.74,"E","飲み物を取って","음료 꺼내","Okay, get my drink out."),
("O",1686.10,1689.10,"C","何にしたの？\\N飲んだことないもの？","뭐 골랐어? 안 마셔 본 거?","What'd you get there? Something you've never had before?"),
("O",1691.96,1694.30,"E","ちょっと飲んでみる","잠깐 마셔 볼게","I'll taste real quick"),
("O",1704.87,1706.95,"B","おつりだよ","거스름돈이야","Here's my change"),
("O",1885.58,1891.08,"C","部屋の明かりは、\\N先につけておきました","방 불은 미리 켜 뒀어요","Movie magic, and all the lights are on in our place. We figured it would be easier..."),
("O",1916.62,1921.68,"E","ビデは、ボタンを押すと\\N水が出るの","비데는 버튼을 누르면 물이 나와요","for the bidet here... You have to push it and turn it on."),
("O",1922.78,1926.32,"E","ふたに当たって、\\Nもう一度押すと止まる","뚜껑에 맞고 한 번 더 누르면 멈춰요","it's hitting the top of the hood. And then you have to press it again to shut it off."),
("O",1942.22,1944.32,"C","手洗いが、\\Nトイレと一体になってる","세면대가 변기와 한 몸이에요","That sink is actually building up the toilet."),
("O",2109.10,2111.78,"E","こっちが私たちの寝室","이쪽이 우리 침실","We do have our bedroom over here."),
("O",2327.70,2333.50,"E","地元のお寿司屋さん。\\Nコナー、入ろう","현지 초밥집이야. 코너, 들어가자","That's one of the local sushi here... Okay Connor, let's go in."),
("O",2359.58,2364.00,"E","このレーンは何？\\N料理がここを通って来るの","이 레인은 뭐야? 음식이 여기로 와","What is this lane? This is where our food's gonna come."),
("O",2373.04,2377.18,"C","でもまずはメニューを見て、\\N食べたいものを選ぼう","그래도 먼저 메뉴 보고 먹고 싶은 걸 고르자","but first I think we need to look over the menu and kind of choose what you want"),
("O",2409.14,2414.24,"E","ご飯が少しのってる。\\Nお寿司の皿","밥이 조금 올라가 있어. 초밥 접시","Oh, it seems like it has a little bit of rice... Sushi plate."),
("O",2452.20,2455.72,"B","ぼくのはもうない","내 건 벌써 없어","Mine's gone. Here you go, go Logan."),
("O",2455.96,2459.00,"B","ソースを頼める？","소스 주문할 수 있어?","Can we order the sauce? There's your sauce."),
("O",2528.32,2533.22,"E","わさびが少しついてくると思ったけど。\\Nもっと調べておけばよかった","와사비가 조금 나올 줄 알았는데. 더 알아볼걸","like a little side of wasabi... I guess we should have done more research"),
("O",2540.32,2542.12,"E","わさびはあるはず","와사비는 있을 거야","Well I know they have wasabi."),
("O",2574.46,2579.88,"E","しょうゆをつけたほうがいい？\\N味が少し足されるよ","간장 찍는 게 나아? 맛이 조금 더해져","Is that better with the soy sauce? Add a little extra flavor for you."),
("O",2584.04,2586.90,"E","唐揚げも、きっと気に入るよ","치킨 가라아게도 분명 좋아할 거야","I think if anything else you're also gonna enjoy the fried chicken."),
("O",2593.32,2596.78,"C","エビ","새우","Leek shrimp or prawn however you want to call it"),
("O",2606.12,2609.84,"E","クリスは気に入りそう。\\Nおいしそう","크리스는 좋아할 것 같아. 맛있어 보여","I think he's gonna enjoy those. Look tasty."),
("O",2696.18,2698.66,"E","辛いのとか？\\N見当たらない","매운 거라든가? 안 보여","Like the spicy? I don't really see any"),
("O",2919.68,2923.74,"C","ずっと気づかなかった","계속 몰랐어","did we not notice that the whole time?"),
("O",3098.14,3100.42,"C","注文した13品が、\\N全部書いてある","주문한 13개가 다 적혀 있어","nicely itemized 13 different items"),
("T",55.71,58.25,"C","これが、私たちの生活のすべて","이게 우리 생활의 전부","this is our our whole life here"),
("T",82.60,88.48,"E","いつも扱いやすいとは限らない。\\Nほら、行くよ","항상 다루기 쉬운 건 아니에요. 자, 가자","and it's not always the easiest to manage all right guys come on"),
("T",104.66,108.54,"E","45キロ、ね","45킬로라","Yeah 100 pounds is what I like."),
("T",291.59,295.51,"E","ネットでも買えるけど、\\N駅でやってもらいました","인터넷으로도 살 수 있지만 역에서 해 달라고 했어요","You can also buy them online, but we just figured we'd go in and have them do it for us"),
("T",385.04,386.54,"E","JRの","JR의","the JR, the Japan train."),
("T",393.60,397.70,"E","チャージできるカードで、\\N一度チャージしました","충전할 수 있는 카드라 한 번 충전했어요","these are cards that are reloadable... we've had to reload them up one time"),
("T",460.17,460.83,"B","ここに入れる？","여기 넣어?","Put it in there?"),
("T",663.49,664.03,"B","速すぎる","너무 빨라","Too fast."),
("T",673.67,677.89,"C","これでも最速の列車じゃない。\\N最速は「はやぶさ」","이것도 가장 빠른 열차가 아니에요. 가장 빠른 건 「하야부사」","this actually isn't even the fastest train. The fastest train is the Hayabusa."),
("T",916.22,919.52,"C","トイレも快適、すごくきれい","화장실도 쾌적하고 아주 깨끗해","Pretty good bathroom experience very clean"),
("T",924.04,927.02,"E","子どもたち、調子はどう？","얘들아, 어때?","are you kids doing pretty good? How are you?"),
]

# --- v1c: 남은 「자막 없음」 보충(시각 넓히기·추가)
ADJ = {("O",2327.70):(None,2335.50,None), ("O",2402.48):(None,2408.80,None), ("O",455.92):(None,460.84,"これがプレミアムの日本のパンケーキ。\\N光って見えにくいけど"),
       ("O",466.12):(465.32,None,None), ("O",488.82):(None,493.10,None), ("O",494.50):(493.82,None,None), ("O",1186.50):(1185.50,None,None),
       ("O",1398.72):(None,1400.44,None), ("O",2593.32):(2592.70,None,"おお、エビ"), ("T",108.96):(None,114.30,None),
       ("T",468.01):(467.20,None,"わかった。場所が違ったのかも"), ("T",916.22):(915.60,None,None), ("O",2414.88):(None,2422.0,None), ("T",663.49):(None,664.45,None), ("T",369.20):(368.00,None,None), ("T",280.37):(279.90,None,None)}
def _adj(e, a, b, j):
    x = ADJ.get((e, a), (None, None, None))
    return x[0] or a, x[1] or b, x[2] or j
C = [(e, *_adj(e, a, b, j)[:2], sp, _adj(e, a, b, j)[2], k, n) for e, a, b, sp, j, k, n in C]
C += [("O",507.88,509.64,"E","ありがとう","고마워요","Thank you."),
      ("O",766.00,767.84,"C","おお、よし","오, 좋아","Aha. All right."),
      ("O",1242.84,1244.64,"E","ローガンは傘で守る気満々","로건은 우산으로 지킬 준비 완료","Logan has his umbrella ready to protect"),
      ("O",2427.90,2430.10,"E","ベジタリアン向けもあった","채식 메뉴도 있었어","actually was able to get some vegetarian options")]

# --- v1d: 대조 시트 검수(2026-10-08) — 화면으로 화자 수정
SPK_FIX = {("T",1018.45):"C", ("T",1090.58):"E", ("T",185.0):"E", ("T",196.5):"E", ("T",265.96):"E", ("T",280.37):"E", ("O",276.74):"E", ("T",279.90):"E"}
C = [(e, a, b, SPK_FIX.get((e, a), sp), j, k, n) for e, a, b, sp, j, k, n in C]

out = [dict(ep=e, s0=a, s1=b, kind="Y", spk=s, ja=j, ko=k, en=n, use=True) for e, a, b, s, j, k, n in C]
json.dump(out, open(__file__.replace(".py", ".json"), "w"), ensure_ascii=False, indent=1)
print(len(out), "cues")
